# Generated by Django 3.1.8 on 2021-05-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('SNO', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('PLACE', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
