# Generated by Django 3.2 on 2021-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowflaketest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
