# Generated by Django 3.2 on 2021-05-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowflaketest', '0002_student_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_at',
            new_name='CREATED_AT',
        ),
    ]
