# Generated by Django 3.2 on 2021-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowflaketest', '0003_rename_created_at_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CREATED_AT',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
